name: Build and Publish to GH Releases

on:
  push:
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    # tags:
    #   - v*

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: ./install_deps.ps1

      - name: Build
        run: ./build.ps1

      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: unrailed-save-scummer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
